"""API configuration loaded from environment variables.

All paths default to the local models/ directory generated by Phase 1.8.
Override via environment variables for alternative deployments.
"""

import os


class Settings:
    def __init__(self) -> None:
        self.model_path: str = os.getenv("MODEL_PATH", "models/best_model.joblib")
        self.model_metadata_path: str = os.getenv(
            "MODEL_METADATA_PATH", "models/model_metadata.json"
        )
        self.feature_schema_path: str = os.getenv(
            "FEATURE_SCHEMA_PATH", "models/feature_schema.json"
        )
        self.api_version: str = os.getenv("API_VERSION", "0.1.0")


settings = Settings()
